name: Issue
description: An issue with one of Streamlink's Windows builds
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting an issue with Streamlink's Windows builds!

        **Issues and questions related to Streamlink itself DO NOT BELONG here and will be closed immediately.**
  - type: dropdown
    attributes:
      label: Build flavor
      options:
        - Installer - Python 3.10 - x86_64 (64 bit)
        - Installer - Python 3.10 - x86 (32 bit)
        - Installer - Python 3.8 - x86_64 (64 bit)
        - Installer - Python 3.8 - x86 (32 bit)
        - Portable - Python 3.10 - x86_64 (64 bit)
        - Portable - Python 3.10 - x86 (32 bit)
        - Portable - Python 3.8 - x86_64 (64 bit)
        - Portable - Python 3.8 - x86 (32 bit)
    validations:
      required: true
  - type: input
    attributes:
      label: Build version
      description: |
        The exact file name of the installer or portable build.
  - type: textarea
    attributes:
      label: Description
      description: |
        Explain the issue as thoroughly as you can and list the steps which lead to the problem.
        Please also provide details about your operating system and its configuration if you can.
    validations:
      required: true
